<a href="https://colab.research.google.com/github/dinuka-rp/Applied-AI/blob/main/Python%20Fundementals/AppledAI_Tut2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys

print(sys.version)
print(sys.path)

3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]
['', '/content', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '/root/.ipython']


In [3]:
# This is a code cell. Press shift-enger to execute it. 
import sys
print(f'Dinuka is using python version {sys.version} on this machine.')

Dinuka is using python version 3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0] on this machine.


# Markdown lets you format text. This is example text printed using Header 1 formatting

In [4]:
print('hello') #code cell

hello


`This is a raw cell. You can copy any code here and it will not be changed. >>> 1 == 0 False >>> not (1 == 0) True >>> (2 == 2) and (2 == 3) False >>> (2 == 2) or (2 == 3) True`

Raw cell can be useful when referencing code in a document or if you want to keep the layout and formatting.

## Change directories using magic commands

In [9]:
# %cd H:/dev
%pwd

'/content'

In [ ]:
# We can add python comments as well. 
# Notice that the state of the environment carries accross cells.

In [7]:
# List all magic commands
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl 

## Now start exploring Python code.

### Operators

In [10]:
print(1+1)
print(2*3)

2
6


### Equality

In [11]:
print(1 == 0)
print(False == 0)
print(True == 8)  #
print("hello" == 'hello')

False
True
False
True


### Strings

Operator overloading and standard set of string libraries.

In [12]:
print('6COSC020W ' + 'Applied ' + 'AI' + '!'*3)
print('applied ai'.upper())
print(len('Artificial Intelligence'))

6COSC020W Applied AI!!!
APPLIED AI
23


### Remember that Python is not statically typed

Variables can be reassigned. This is convenient but dangerous with larger programs.

In [13]:
s = "Westminster Uni has a great selection of Options!"
print (s)
s = 25
print(s)

Westminster Uni has a great selection of Options!
25


In [14]:
s = 'Applied AI'
print(s.find('AI'))
help(s.find)

8
Help on built-in function find:

find(...) method of builtins.str instance
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.



### Dir and Help

Dir lists all the members of an object. Help is a convenient way to lookup a method.

In [18]:
s = 'ai'
#try dir(s) and help() on any of the string methods.
print(dir(s))
help(s.lower)

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
Help on built-in function lower:

lower() method of builtins.str in

### Data Structures

Lists, Tuples, Sets, Dictionaries

Lists are a sequence of mutable items. Tuples Sets are Dictionaries

In [19]:
colours = ['red', 'orange', 'yellow', 'green', 'blue']
print(colours[0])
print(colours[-1]) # negative indexing
colours[1] # returns the string at location 1
colours[0] = 'purple'
colours[0]

print(dir(colours))

red
blue
['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


Slice operator to index multiple elements.

In [ ]:
colours[2:4] #gets elements 2,3

### Tuples

Like a list but immutable once created. Uses '()' instead of '[]'

In [20]:
point = (2,3)
x, y = point
print(f'Point({x},{y})')
# point[0] = 3 #This will not work!

Point(2,3)


### Sets

Also like a list, but unordered and does not allow duplicate items.

In [21]:
room1 = {'chair', 'table', 'spoon'}
room2 = {'chair', 'bed', 'plate', 'spoon'}
print(room1, room2)
print('spoon' in room1) 
print(room1.intersection(room2))
print(room1.union(room2))

{'chair', 'spoon', 'table'} {'plate', 'chair', 'bed', 'spoon'}
True
{'chair', 'spoon'}
{'spoon', 'bed', 'plate', 'chair', 'table'}


### Dictionaries

A map of key value pairs. The key must be immutable (string, number, or tuple). Value can be any type.

In [22]:
order = {'apples':5, 'oranges':3, 'lemons':2}
print(order['oranges'])
order['oranges'] += 5
print(f"I ordered {order['oranges']} oranges")
print(order.keys(), order.values())

3
I ordered 8 oranges
dict_keys(['apples', 'oranges', 'lemons']) dict_values([5, 8, 2])


### Input

In [23]:
a = input("Enter your name: ")
print(f"Hello {a}")

Enter your name: Dinuka
Hello Dinuka


### Input from a file

In [45]:
f = open("temp.ipynb", "r")
print(f.read())

### The range() function

The range () function returns a sequence of numbers, starting from zero, increments by one, and ends at a specified number.

In [25]:
for n in range(10):
    print(n)

0
1
2
3
4
5
6
7
8
9


In [27]:
for n in range(3,10):
    print(n)

3
4
5
6
7
8
9


In [28]:
for n in range(3,10,2):
    print(n)

3
5
7
9


### List comprehensions

List comprehensions are an elegant and readable way to create lists.

In [29]:
evens = [x for x in range(10) if x%2 == 0]
print(evens)

[0, 2, 4, 6, 8]


Exercise: Write a list comprehension that creates a list of the squares of the odd numbers.

In [33]:
odds = [x for x in range(10) if x%2 != 0]
print(odds)

square_odd = [x**2 for x in range(10) if x%2 != 0]
print(square_odd)

[1, 3, 5, 7, 9]
[1, 9, 25, 49, 81]


### Classes and Objects

In [34]:
class FruitShop:

    def __init__(self, name, fruitPrices):
        """
            name: Name of the fruit shop

            fruitPrices: Dictionary with keys as fruit
            strings and prices for values e.g.
            {'apples': 2.00, 'oranges': 1.50, 'pears': 1.75}
        """
        self.fruitPrices = fruitPrices
        self.name = name
        print('Welcome to %s fruit shop' % (name))

    def getCostPerPound(self, fruit):
        """
            fruit: Fruit string
        Returns cost of 'fruit', assuming 'fruit'
        is in our inventory or None otherwise
        """
        if fruit not in self.fruitPrices:
            return None
        return self.fruitPrices[fruit]

    def getPriceOfOrder(self, orderList):
        """
            orderList: List of (fruit, numPounds) tuples

        Returns cost of orderList, only including the values of
        fruits that this fruit shop has.
        """
        totalCost = 0.0
        for fruit, numPounds in orderList:
            costPerPound = self.getCostPerPound(fruit)
            if costPerPound != None:
                totalCost += numPounds * costPerPound
        return totalCost

    def getName(self):
        return self.name

In [35]:
shopName = 'the Berkeley Bowl'
fruitPrices = {'apples': 1.00, 'oranges': 1.50, 'pears': 1.75}
berkeleyShop = FruitShop(shopName, fruitPrices)
applePrice = berkeleyShop.getCostPerPound('apples')
print(applePrice)
print('Apples cost $%.2f at %s.' % (applePrice, shopName))

otherName = 'the Stanford Mall'
otherFruitPrices = {'kiwis': 6.00, 'apples': 4.50, 'peaches': 8.75}
otherFruitShop = FruitShop(otherName, otherFruitPrices)
otherPrice = otherFruitShop.getCostPerPound('apples')
print(otherPrice)
print('Apples cost $%.2f at %s.' % (otherPrice, otherName))
print("My, that's expensive!")

Welcome to the Berkeley Bowl fruit shop
1.0
Apples cost $1.00 at the Berkeley Bowl.
Welcome to the Stanford Mall fruit shop
4.5
Apples cost $4.50 at the Stanford Mall.
My, that's expensive!


### A taste of numpy
NumPy is a fundamental package frequequntly used for scientific computing in Python.

In [36]:
import numpy as np

a=np.arange(3)
print(a)

[0 1 2]


In [37]:
c = np.arange(24).reshape(2, 3, 4) 
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [42]:
a**2
# print(a**2)

array([0, 1, 4])

In [39]:
c**2

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]])